## Preprocessing

In [74]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import tensorflow as tf


#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [75]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [76]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [77]:
# Identify target and features
# Assume 'IS_SUCCESSFUL' is the target variable
X = application_df.drop('IS_SUCCESSFUL', axis=1)
y = application_df['IS_SUCCESSFUL']

In [78]:
# Determine the number of unique values in each column.
print(X.nunique())

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
dtype: int64

In [79]:
# For columns with more than 10 unique values, print the count for each unique value
for col in X.columns:
    if X[col].nunique() > 10:
        print(f"Column: {col}\n", X[col].value_counts())

Column: APPLICATION_TYPE
 APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64
Column: CLASSIFICATION
 CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64
Column: ASK_AMT
 ASK_AMT
5000        25398
10478           3
15583           3
63981           3
6725            3
            ...
5371754         1
30060           1
43091152        1
18683           1
36500179        1
Name: count, Length: 8747, dtype: int64

In [80]:
# View the unique values and their counts in the 'APPLICATION_TYPE' column
print(application_df['APPLICATION_TYPE'].value_counts())

# Choose a cutoff value (e.g., applications with fewer than 100 occurrences)
cutoff_value = 100

# Create a list of application types to replace with 'Other'
application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < cutoff_value].index.tolist()

# Replace these application types with 'Other' in the dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Step 5: Check to ensure the replacement was successful
print(application_df['APPLICATION_TYPE'].value_counts())

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64
APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [81]:
# View the unique values and their counts in the 'APPLICATION_TYPE' column
print(application_df['APPLICATION_TYPE'].value_counts())

# Choose a cutoff value (e.g., applications with fewer than 100 occurrences)
cutoff_value = 100

# Create a list of application types to replace with 'Other'
application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < cutoff_value].index.tolist()

# Replace these application types with 'Other' in the dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Step 5: Check to ensure the replacement was successful
print(application_df['APPLICATION_TYPE'].value_counts())

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64
APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [82]:
# You may find it helpful to look at CLASSIFICATION value counts > 1
# Step 1: Check the columns present in your DataFrame
print("Columns in DataFrame:", application_df.columns)

# Step 2: Check if the 'CLASSIFICATION' column exists in the DataFrame
if 'CLASSIFICATION' in application_df.columns:
    # Step 3: If the column exists, print the unique value counts
    classification_counts = application_df['CLASSIFICATION'].value_counts()
    print("CLASSIFICATION Value Counts:\n", classification_counts)

    # Step 4: Filter and display classifications with more than 1 occurrence
    classifications_gt1 = classification_counts[classification_counts > 1]
    print("\nCLASSIFICATION Value Counts > 1:\n", classifications_gt1)
else:
    # Step 5: If the column does not exist, print a message
    print("Column 'CLASSIFICATION' not found in the DataFrame.")

Columns in DataFrame: Index(['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS',
       'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')
CLASSIFICATION Value Counts:
 CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

CLASSIFICATION Value Counts > 1:
 CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [83]:
# View the unique values and their counts in the 'APPLICATION_TYPE' column
print(application_df['APPLICATION_TYPE'].value_counts())

# Choose a cutoff value (e.g., applications with fewer than 100 occurrences)
cutoff_value = 100

# Create a list of application types to replace with 'Other'
application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < cutoff_value].index.tolist()

# Replace these application types with 'Other' in the dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")
application_df.head()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [84]:
# Step 5: Check to ensure the replacement was successful
print(application_df['APPLICATION_TYPE'].value_counts())

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [85]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)

In [86]:
# Split our preprocessed data into our features (X) and target (y) arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1).values  # Features array
y = application_df['IS_SUCCESSFUL'].values  # Target array

# Split the preprocessed data into a training and testing dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Confirm the shapes of the datasets to ensure the split was successful
print(f"Training Features Shape: {X_train.shape}")
print(f"Testing Features Shape: {X_test.shape}")
print(f"Training Target Shape: {y_train.shape}")
print(f"Testing Target Shape: {y_test.shape}")

Training Features Shape: (27439, 109)
Testing Features Shape: (6860, 109)
Training Target Shape: (27439,)
Testing Target Shape: (6860,)

In [87]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler on the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Confirm the scaling worked by checking the shape of the scaled data
print(f"Scaled Training Features Shape: {X_train_scaled.shape}")
print(f"Scaled Testing Features Shape: {X_test_scaled.shape}")

Scaled Training Features Shape: (27439, 109)
Scaled Testing Features Shape: (6860, 109)

## Compile, Train and Evaluate the Model

In [88]:
# Define the model - deep neural network
nn = tf.keras.models.Sequential()

# First hidden layer
# Input layer: Number of input features equals the number of columns in X_train_scaled
input_features = X_train_scaled.shape[1]
nn.add(tf.keras.layers.Dense(units=80, input_dim=input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
# Binary classification, so we use 1 unit with a 'sigmoid' activation function
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                      │ (None, 80)                  │           8,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 30)                  │           2,430 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 1)                   │              31 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 11,261 (43.99 KB)

 Trainable params: 11,261 (43.99 KB)

 Non-trainable params: 0 (0.00 B)

In [93]:
# Compile the model
nn.compile(optimizer='adam',
           loss='binary_crossentropy',
           metrics=['accuracy'])

# Train the model
history = nn.fit(X_train_scaled, y_train,
                 epochs=50,
                 batch_size=32,
                 validation_split=0.2)

Epoch 1/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7372 - loss: 0.5353 - val_accuracy: 0.7418 - val_loss: 0.5529
Epoch 2/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7323 - loss: 0.5371 - val_accuracy: 0.7420 - val_loss: 0.5518
Epoch 3/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7441 - loss: 0.5285 - val_accuracy: 0.7402 - val_loss: 0.5543
Epoch 4/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7409 - loss: 0.5302 - val_accuracy: 0.7420 - val_loss: 0.5526
Epoch 5/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7371 - loss: 0.5320 - val_accuracy: 0.7436 - val_loss: 0.5556
Epoch 6/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7410 - loss: 0.5304 - val_accuracy: 0.7418 - val_loss: 0.5521
Epoch 7/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7395 - loss: 0.5326 - val_accuracy: 0.7411 - val_loss: 0.5540
Epoch 8/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7383 - loss: 0.5349 - val_accuracy: 0.7429 - val_loss: 0.5565
Epoch 9/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7380 - loss: 0.5338 - val_accuracy: 0.7414 - val_loss: 0.5561
Epoch 10/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7376 - loss: 0.5280 - val_accuracy: 0.7409 - val_loss: 0.5551
Epoch 11/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7403 - loss: 0.5335 - val_accuracy: 0.7402 - val_loss: 0.5519
Epoch 12/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7381 - loss: 0.5326 - val_accuracy: 0.7400 - val_loss: 0.5535
Epoch 13/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7449 - loss: 0.5253 - val_accuracy: 0.7413 - val_loss: 0.5612
Epoch 14/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7424 - loss: 0.5276 - val_accuracy: 0.7413 - val_loss: 0.5539
Epoch 15/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7398 - loss: 0.5324 - val_accuracy: 0.7418 - val_loss: 0.5560
Epoch 16/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7387 - loss: 0.5286 - val_accuracy: 0.7402 - val_loss: 0.5537
Epoch 17/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7393 - loss: 0.5333 - val_accuracy: 0.7402 - val_loss: 0.5613
Epoch 18/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7360 - loss: 0.5341 - val_accuracy: 0.7416 - val_loss: 0.5591
Epoch 19/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7371 - loss: 0.5332 - val_accuracy: 0.7433 - val_loss: 0.5549
Epoch 20/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7389 - loss: 0.5313 - val_accuracy: 0.7403 - val_loss: 0.5555
Epoch 21/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7474 - loss: 0.5231 - val_accuracy: 0.7403 - val_loss: 0.5576
Epoch 22/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7408 - loss: 0.5287 - val_accuracy: 0.7407 - val_loss: 0.5553
Epoch 23/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7378 - loss: 0.5320 - val_accuracy: 0.7405 - val_loss: 0.5587
Epoch 24/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7414 - loss: 0.5296 - val_accuracy: 0.7418 - val_loss: 0.5592
Epoch 25/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7455 - loss: 0.5225 - val_accuracy: 0.7409 - val_loss: 0.5620
Epoch 26/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7419 - loss: 0.5298 - val_accuracy: 0.7427 - val_loss: 0.5562
Epoch 27/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7407 - loss: 0.5281 - val_accuracy: 0.7407 - val_loss: 0.5541
Epoch 28/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7368 - loss: 0.5320 - val_accuracy: 0.7402 - val_loss: 0.5592
Epoch 29/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7453 - loss: 0.5270 - val_accuracy: 0.7394 - val_loss: 0.5550
Epoch 30/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7398 - loss: 0.5300 - val_accuracy: 0.7423 - val_loss: 0.5587
Epoch 31/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7474 - loss: 0.5261 - val_accuracy: 0.7425 - val_loss: 0.5594
Epoch 32/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7445 - loss: 0.5273 - val_accuracy: 0.7391 - val_loss: 0.5562
Epoch 33/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7452 - loss: 0.5261 - val_accuracy: 0.7394 - val_loss: 0.5581
Epoch 34/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7382 - loss: 0.5295 - val_accuracy: 0.7422 - val_loss: 0.5613
Epoch 35/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7434 - loss: 0.5279 - val_accuracy: 0.7418 - val_loss: 0.5601
Epoch 36/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7441 - loss: 0.5249 - val_accuracy: 0.7400 - val_loss: 0.5663
Epoch 37/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7406 - loss: 0.5283 - val_accuracy: 0.7363 - val_loss: 0.5577
Epoch 38/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7362 - loss: 0.5308 - val_accuracy: 0.7414 - val_loss: 0.5685
Epoch 39/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7416 - loss: 0.5275 - val_accuracy: 0.7422 - val_loss: 0.5630
Epoch 40/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7439 - loss: 0.5260 - val_accuracy: 0.7400 - val_loss: 0.5604
Epoch 41/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7433 - loss: 0.5268 - val_accuracy: 0.7418 - val_loss: 0.5701
Epoch 42/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7426 - loss: 0.5284 - val_accuracy: 0.7400 - val_loss: 0.5637
Epoch 43/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7401 - loss: 0.5265 - val_accuracy: 0.7420 - val_loss: 0.5638
Epoch 44/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7389 - loss: 0.5298 - val_accuracy: 0.7414 - val_loss: 0.5591
Epoch 45/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7458 - loss: 0.5257 - val_accuracy: 0.7413 - val_loss: 0.5606
Epoch 46/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7353 - loss: 0.5337 - val_accuracy: 0.7420 - val_loss: 0.5648
Epoch 47/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7447 - loss: 0.5246 - val_accuracy: 0.7382 - val_loss: 0.5639
Epoch 48/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7385 - loss: 0.5302 - val_accuracy: 0.7429 - val_loss: 0.5863
Epoch 49/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7411 - loss: 0.5299 - val_accuracy: 0.7416 - val_loss: 0.5681
Epoch 50/50
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7443 - loss: 0.5264 - val_accuracy: 0.7394 - val_loss: 0.5679

### Evaluate model using Test or Model

In [94]:
# Evaluate the model using the test data
test_loss, test_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

215/215 - 0s - 2ms/step - accuracy: 0.7268 - loss: 0.5659

In [91]:
# Evaluate the model's performance on the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test)

215/215 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7254 - loss: 0.5599

In [92]:
# Export the trained model to an HDF5 file
nn.save('AlphabetSoupCharity.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.